name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unit-retrieval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH
        shell: bash
        run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Sync deps
        run: uv sync

      - name: Run retrieval test (offline)
        run: uv run python -m tests.test_retrieval